layout_spectrum: 0.24193450435996056
typography_spectrum: 0.12080746819265187
color:
  brandStrength: 0.1081454330123961
  lightness: 0.9150199012365192
  saturation: 0.6338092023506761
  rhythmicContrast: 0.7436410184018314
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
content_rating:
  adult: false
author:
  name: Joseph Paiva
  email: josephpaiva1985@gmail.com
name: Joseph Arts
navigation:
  - name: Sobre
    id: 3a58b865-1c66-4dec-b8ba-4196de142210
    type: content
title: Joseph Arts
description: Ilustrador Freelancer
