typography_spectrum: 0.4621018785983324
content_rating:
  adult: false
color:
  brandStrength: 0.7789925667457283
  lightness: 0.3474581732880324
  saturation: 0.8800002785865217
  rhythmicContrast: 0.30851577990688384
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.6072273436002433
author:
  name: Joseph Paiva
  email: josephpaiva1985@gmail.com
name: Joseph Arts
title: Joseph Arts
description: Ilustrador Freelancer
