typography_spectrum: 0.5481779586989433
content_rating:
  adult: false
color:
  brandStrength: 0.7556145540438592
  lightness: 0.6183763707522303
  saturation: 0.2824257502797991
  rhythmicContrast: 0.29156104871071875
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.7796663125045598
author:
  name: Joseph Paiva
  email: josephpaiva1985@gmail.com
name: Joseph Arts
navigation:
  - name: Sobre
    id: 3a58b865-1c66-4dec-b8ba-4196de142210
    type: content
  - name: Dark Arts
    id: 4ce5256e-fb8e-41e7-9e1a-eaa35beed034
    type: content
title: Joseph Arts
description: Ilustrador Freelancer
